/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.loern.tutorial;
/**
 * author: andy
 * class App
 */
public class App {
  /**
   * getGreeting method 
   */
    public String getGreeting() {
        return "Hello World!";
    }
  /**
    * main method 
    */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
